### ISSUE TITLE
[providence-analytics]  Providence analyze config file on windows

### ISSUE THREAD

**Issue by mrzbigniew** [ing-bank/lion#1548]
## Expected behavior

Providence should load config on windows as on other operating systems and run analyze 

## Actual Behavior

Providence fails on Window with error:
```
node:internal/errors:464
    ErrorCaptureStackTrace(err);
    ^

Error [ERR_UNSUPPORTED_ESM_URL_SCHEME]: Only file and data URLs are supported by the default ESM loader. On Windows, absolute paths must be valid file:// URLs. Received protocol 'd:'
    at new NodeError (node:internal/errors:371:5)
    at Loader.defaultResolve [as _resolve] (node:internal/modules/esm/resolve:1016:11)
    at Loader.resolve (node:internal/modules/esm/loader:89:40)
    at Loader.getModuleJob (node:internal/modules/esm/loader:242:28)
    at Loader.import (node:internal/modules/esm/loader:177:28)
    at importModuleDynamically (node:internal/modules/esm/translators:115:35)
    at exports.importModuleDynamicallyCallback (node:internal/process/esm_loader:30:14)
    at getProvidenceConf (file:///***/node_modules/providence-analytics/src/program/utils/get-providence-conf.mjs:25:39)
    at file:///***/node_modules/providence-analytics/src/cli/index.mjs:7:36
    at file:///***/node_modules/providence-analytics/src/cli/index.mjs:9:3 {
  code: 'ERR_UNSUPPORTED_ESM_URL_SCHEME'
}
```

## Additional context

```
"providence-analytics": "^0.12.1"
```
Can be fixed by adding [pathToFileURL](https://nodejs.org/api/url.html#urlpathtofileurlpath)

## Pull request
#1555

**Comment by tlouisse** [comment]
Thanks for testing this in windows and thanks for suggesting a fix as well. I'm off til Monday, but please feel free to do a pull request :)

**Comment by tlouisse** [comment]
Fixed by https://github.com/ing-bank/lion/pull/1555
